### ISSUE TITLE
Remove particles command (FEATURE)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#100]
HOW I can remove the particle on the player with chestcommands? Maybe a command like: ./removeparticles playername

Samething for all other cosmetics ooptions will be great

So it can be: ./removehat playername

This allow me to completely rebuild the GUI but with chestcommands ;)
It look better and a much better thatn the ultimatecosmectis GUI :)

Thank you

**Comment by j0ach1mmall3** [comment]
Those commands already exist...
