### ISSUE TITLE
serious bug

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#101]
got a random disconect from mysql with UC for the last 3 updates,, its kiling us need it fixed, techy checked its not our mysql no other plugins drop just this then it takes down the server

https://gyazo.com/80e7765906f9ea5f40d0663669ba6cf7
https://gyazo.com/05d3698e8228045e70030011a7771777
https://gyazo.com/b0c14ff8da1a0f3105efdd797cc12638

**Comment by j0ach1mmall3** [comment]
Should be fixed with newest JLib
