### ISSUE TITLE
Spawn Eggs 1.9

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#104]
How do I need to format the pets?
373:<potid> returns an unknown block (the purple/black one)

and the pets eggs:
383:<entityid> they all return a white egg.

This did work in 1.8

Thanks in advance,
CB

**Comment by j0ach1mmall3** [comment]
ID:DATA is the format

**Comment by j0ach1mmall3** [comment]
Potions will be fixed in newest JLib.
Pet Eggs still need some time since there's no official API.

**Comment by j0ach1mmall3** [comment]
Nvm that, it will need to wait some more untill the official spigot jar has it. For now only the API has the potion stuff

**Comment by j0ach1mmall3** [comment]
Potions are already available in JLib, by using https://github.com/j0ach1mmall3/JLib/wiki/The-new-Item-Format#potion-effect

**Comment by drekryan** [comment]
These resources may be helpful for Spawn Eggs in 1.9 

https://github.com/essentials/Essentials/pull/788/commits/767abe83f9b6971023e129a4333bc99f366d6373#diff-e4c0b48a6c8c5222605cbd4b645c92ffR149

https://github.com/tastybento/askyblock/blob/3.0.0/src/com/wasteofplastic/askyblock/util/SpawnEgg1_9.java

**Comment by j0ach1mmall3** [comment]
Will be fixed in the latest JLib build
