### ISSUE TITLE
Information about cosmetics very strange saved.

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#11]
I do not know how to explain it. just watch the video

Latest version spigot
Latest version UC

https://youtu.be/nYY4KFRS1PU

**Comment by j0ach1mmall3** [comment]
What's wrong with it?
Is there anything not functioning?

**Comment by Toshka17** [comment]
If you choose to itself any head (block) or a banner, when reconnecting to the server plugin can no longer control it. It is impossible to remove it from the head, or be replaced by another block.

For example with bow_trails all right

**Comment by Toshka17** [comment]
Latest updates did not solve the problem

**Comment by j0ach1mmall3** [comment]
I don't really understand what you mean by 'plugin can no longer control it'

**Comment by Toshka17** [comment]
You watched the video?
Ohhhhh... English.. I will make two more movies, so I could understand

**Comment by Toshka17** [comment]
Not normal with banners, hats, baloons: https://youtu.be/o0Xl2HtPNI0
                                                                https://youtu.be/gLGJ2kU7b0E

Normal with bow trails: https://youtu.be/jtx0XOHAO7U

**Comment by j0ach1mmall3** [comment]
That's a really strange issue, are you in offline mode bungeecord? Maybe it has something to do with uuids. I'll investigate it

**Comment by Toshka17** [comment]
But with bowtrails everything works well, and with the other is not on the same player, as seen in the video. So the problem is not with the UUID

**Comment by j0ach1mmall3** [comment]
Will be fixed in the next update

**Comment by j0ach1mmall3** [comment]
Check the latest update please

**Comment by Toshka17** [comment]
Hmm ... now plugin does not store information

**Comment by Toshka17** [comment]
Now, any information is not stored. Mysql, nothing happens

**Comment by IlPicasso** [comment]
I have this problem, when I buy AMMO it is saved but when I use it it is not substracted, also when using a gadget or anything it is not saved to mysql so when moving of server it won't use the gadgets used in the last server

**Comment by j0ach1mmall3** [comment]
Mhm, I will try to fix this asap.

**Comment by j0ach1mmall3** [comment]
Mhm, the queue works for me though. I'll try to remove the async and see what it does. It might come with performance drawbacks though

**Comment by j0ach1mmall3** [comment]
Weird, I never changed anything to the ammo system so idk how that's a problem.

**Comment by j0ach1mmall3** [comment]
Oh, it's a visual bug the ammo reduction. It does in fact reduce the ammo though!

**Comment by Toshka17** [comment]
Yeaaah you did it! Thanks!

**Comment by Toshka17** [comment]
By the way, when you select a banner, for some reason he is not highlighted enchantment, not like the rest cosmetic bonuses

**Comment by j0ach1mmall3** [comment]
That's a minecraft issue

**Comment by IlPicasso** [comment]
Storage seems to be working now for me

**Comment by IlPicasso** [comment]
@j0ach1mmall3 

       6.80%	 259.63%	636.74 s	   129.81 ms	 0.0	       4.9k	    d::a(PlayerJoinEvent)
The playerJoinevent seems to be intensive again

http://timings.aikar.co/?url=13334569
