### ISSUE TITLE
giveparticles myname particlename console error

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#111]
I have spigot 1.8.8, java 8 and latest ultimatecosmetics version

http://pastebin.com/5yhhQ9Xn

I try to giveme particles with the command and I get this error ^^^^

This is bad, because I can't create a chest-command gui with this to fully customize my menus :(

Thanks again if you can or help me to fix this

**Comment by j0ach1mmall3** [comment]
Wait untill 4.0.0 is out, maybe it fixes your issue
