### ISSUE TITLE
1.8 server bug with 4.0.0 ultimates cosmetics and latest jlib

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#114]
Each time someone join my server with Spigot 1.8.8, I see thisin the console:
http://pastebin.com/x6xie2Cu

Any way to fix this? It seems to cme from jlib and ultimatecosmetics

Thanks again

**Comment by maxlehot1234** [comment]
@j0ach1mmall3 
Any update when you wake-up or when you have time pleased? It is very bad to release something with 1 examples per cosmeticxs and a bug that spam my console....

**Comment by maxlehot1234** [comment]
Sorry, I get this error again, but I found when it happens..
It happens when I load the server and try to reload the plugin to edit the config files.
It reload find and all works good, but directly when someone join the server, I get the error...

It seems to be related to the joinevents.

I have a spigot 1.8.8 server.

Thanks again and sorry for the spam and issue spam.....

**Comment by j0ach1mmall3** [comment]
Will look into it. Please post output of /uc debug

**Comment by j0ach1mmall3** [comment]
Whoops

**Comment by maxlehot1234** [comment]
./uc debug give me this error: http://pastebin.com/URTSP9db

I don't know why :P so I can't send you a debug

**Comment by j0ach1mmall3** [comment]
Will be fixed in the newest version.
