### ISSUE TITLE
1.9 morphs

### ISSUE THREAD

**Issue by elliswin** [j0ach1mmall3/UltimateCosmetics#115]
Just purchased and installed all recommended plugins latest versions and when attempting to use the example morph I get the follow console error:

(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:13:45 [Server] INFO org.bukkit.event.EventException
19.03 01:13:45 [Server] ERROR Could not pass event InventoryClickEvent to UltimateCosmetics v4.0.0
19.03 01:13:45 [Server] INFO at java.lang.Thread.run(Thread.java:745)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
19.03 01:13:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.03 01:13:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33)
19.03 01:13:45 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1852)
19.03 01:13:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
19.03 01:13:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
19.03 01:13:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.03 01:13:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
19.03 01:13:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497)
19.03 01:13:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.03 01:13:45 [Server] INFO at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
19.03 01:13:45 [Server] INFO at com.j0ach1mmall3.ultimatecosmetics.GuiHandler.onInventoryClick(GuiHandler.java:44)
19.03 01:13:45 [Server] INFO at com.j0ach1mmall3.ultimatecosmetics.config.CosmeticConfig.handleClick(CosmeticConfig.java:177)
19.03 01:13:45 [Server] INFO at com.j0ach1mmall3.ultimatecosmetics.api.Cosmetic.give(Cosmetic.java:51)
19.03 01:13:45 [Server] INFO at com.j0ach1mmall3.ultimatecosmetics.modules.morphs.Morph.giveInternal(Morph.java:29)
19.03 01:13:45 [Server] INFO at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:18)
19.03 01:13:45 [Server] INFO at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:28)
19.03 01:13:45 [Server] INFO at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:91)
19.03 01:13:45 [Server] INFO java.lang.NullPointerException
19.03 01:13:38 [Server] INFO Admins: ~EllisWin
19.03 01:13:38 [Server] INFO CONSOLE issued server command: /list 

Clear log

   I attempted to use the /uc debug command which failed with this error:

19.03 01:16:37 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
19.03 01:16:37 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'uc' in plugin UltimateCosmetics v4.0.0
19.03 01:16:37 [Server] ERROR null
19.03 01:16:37 [Server] INFO EllisWin issued server command: /uc debug

**Comment by j0ach1mmall3** [comment]
Will look into it, do you have the /uc debug output?

**Comment by j0ach1mmall3** [comment]
Maybe Libsdisguises isn't updated for 1.9 yet

**Comment by j0ach1mmall3** [comment]
Will be partially fixed in the newest version.
