### ISSUE TITLE
1.9 pets creeper causing explosion and damage

### ISSUE THREAD

**Issue by elliswin** [j0ach1mmall3/UltimateCosmetics#116]
when returning to the server having previously had a creeper as a pet, the creeper behaves as a standard creeper exploding next to you and causing damage to area.

**Comment by j0ach1mmall3** [comment]
Will also look into ig

**Comment by j0ach1mmall3** [comment]
*it

**Comment by j0ach1mmall3** [comment]
Can't confirm, will need extra info, repost when 4.0.1 is out please, with /uc debug
