### ISSUE TITLE
Particles command DOESN'T WORK  (4.0.0)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#118]
Hi, I try to open the particles gui, but it simply doesn't work when I use ./cosmetics command and click on the particles item in the gui.

So I try to open the particles menu with: ./particles command.
Same problem. Command not found...

Is it possible for you to fix this as soon as possible?

Thank you.
PS: I prefer to create 1 issue per problem instead of put all of them in 1 issue.

**Comment by j0ach1mmall3** [comment]
Did you enable particles?

**Comment by maxlehot1234** [comment]
Yes of course they are enable in the config and I have libsdisguises install.

**Comment by j0ach1mmall3** [comment]
Afaik, you don't need libsdisguises for Particles, they still work for me, so I'll wait on the /uc debug output
