### ISSUE TITLE
Disconnect chat and console character bug (4.0.0)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#119]
Hi, this is what I get when someone disconnect from my server in the console:
http://imgur.com/vGVGZ2f

And this is what others players see in the chat:
http://imgur.com/KnQn0IT

When I remove your plugin (UltimateCosmetics) from my server, I never get these weird messages again...

If you can fix this error too, it would be very nice.
Thanks again

**Comment by j0ach1mmall3** [comment]
Seems like either a debug message or a bug. Will look into it

**Comment by hazycraft** [comment]
I get the name exact messages spammed in chat when players disconnect had to disabled ultimate cosmetics for now.

**Comment by j0ach1mmall3** [comment]
I think I know what's causing it. I will fix it later today

**Comment by maxlehot1234** [comment]
Ok, I wait the next version ;)

**Comment by j0ach1mmall3** [comment]
Will be fixed in the newest version.
