### ISSUE TITLE
aura still dont work goes into infinite loop of disconnecting player

### ISSUE THREAD

**Issue by hazycraft** [j0ach1mmall3/UltimateCosmetics#120]
whenever I try to enable the aura it just kicks me and then infinite kicks me until I restart the server and delete the ultimate cosmetics folder and regenerate a fresh one. Otherwise it wont let me log in my own server. Major issues still.
https://gist.github.com/anonymous/5365d6fbe6c8d007d110
error: http://pastebin.com/Y7ejrQhy

**Comment by maxlehot1234** [comment]
I think it is not related to ultimatescosmetics?

You have the latest spigot 1.9 server version?
Try updating spigot can fix this issue maybe.

Try update ultimatecosmetics.
Maybe a starter log will be nice to checkif we have an error when the plugin load

Nothing was related to ultimatecosmetics in your pastebin error

**Comment by hazycraft** [comment]
It is related to ultimate cosmetics cause I've loaded server with only ultimate cosmetics and jlib and lastest spigot 1.9 and as soon as I click to activate aura It will dc the player and then they have to log back in and aura never activates. 
If RemoveCosmeticsOnLogOut: false is active then you go into an endless loop of disconnects not being able to do anything except alt + F4. There is no error that pops up in logs or console from ultimate cosmetics.
Please look into this more for spigot 1.9 server there is a compatibility issue somewhere.
I'm using UGlow for auras now until this gets fixed.

**Comment by maxlehot1234** [comment]
It works great for me WITHOUT any errors...I run a spigot 1.9 server with latest jlib, Ultimatescosmetics, spigot 1.9 version and java 8...

But it can maybe happen to some people...

**Comment by hazycraft** [comment]
I'm running on java 8 aswell

**Comment by j0ach1mmall3** [comment]
Try running it on a brand new 1.9 server, maybe it's your server properties

**Comment by hazycraft** [comment]
Alright I did some more testing. My conclusion is If you are running your server in Bungeecord IE Offline mode then auras will not work properly and kick the player. As soon as I made server online mode auras worked without kicking me. Please fix conflicting issues with bungeecord as all my servers run in offline mode.

**Comment by j0ach1mmall3** [comment]
Okie, will look into it

**Comment by hazycraft** [comment]
I found that the error shows in bungeecord http://pastebin.com/Z29uZnbU

**Comment by j0ach1mmall3** [comment]
I don't think there's a way to fix this

**Comment by hazycraft** [comment]
Yes, I'm using the latest bungeecord version. I have used a plugin called UGlow https://www.spigotmc.org/resources/uglow-1-9.19520/ in the past which worked perfectly for glows so I know glows/auras work in offline servers. It seems that ultimate cosmetics is sending data to the bungeecord server to retrieve scoreboard information instead of being local to the server? I do use featherboard for a scoreboard plugin, but I don't think thats the issue because the auras/glows in ultimate cosmetics work perfect on my server as soon as I put a server in online mode.

**Comment by j0ach1mmall3** [comment]
I think the problem is that I fake scoreboard data sent to the player so it wouldn't interfer with a local scoreboard. Bungeecord probably duplicates those packets and sends them all over the network, probably causing that bug

**Comment by hazycraft** [comment]
Is there a way you can make a similar method to how uglow does it? 
What about using effects on player like this http://pastebin.com/TLU6bumw

**Comment by j0ach1mmall3** [comment]
That doesn't set the color, only the glow, for the color you need scoreboard teams

**Comment by j0ach1mmall3** [comment]
I'll try to fix it in the latest update

**Comment by j0ach1mmall3** [comment]
Can someone confirm whether this is still an issue?
