### ISSUE TITLE
No cosmetics works  (4.0.1)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#121]
Hi, no cosmetics works. All cosmetics gui items doesn't works.

I try ./particles and still doesn't work....

So the plugin just doesn't work for me...

This is my uc debug: https://gist.github.com/anonymous/955b6cb7f224b1409995

If you can fix this, it could be very nice, because now the lpugin was just not usable...

I also try into my 1.9 test server with your default files and all works for 1.9 server.
So it is an issue with 1.8 server

**Comment by j0ach1mmall3** [comment]
Is there an error?

**Comment by maxlehot1234** [comment]
No nothing. Just command not found, like if the plugin doesn't include commands :P

But all works great in 1.9....


So it is related to 1.8.8 :(

**Comment by j0ach1mmall3** [comment]
Ok, I'll try to fix it

**Comment by maxlehot1234** [comment]
Not a big deal for me, because I finish my 1.9 server setup, but for all other buyers, it could be a big problem.
Maybe a different jar for 1.8 and another one 1.9 will fix all problems.

I know it is long to developp but this could fix a big part of bugs between the 2 version ;)


It is my point

**Comment by j0ach1mmall3** [comment]
Interesting, the balloons work, but the others don't

**Comment by j0ach1mmall3** [comment]
Found the issue, everything was disabling if Auras were disabled!

**Comment by maxlehot1234** [comment]
Any way to fix this in the next version? ;)
