### ISSUE TITLE
Potions doesn't work (morph)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#122]
Hi, I try to use potions in my 1.9 server and I get this:
http://pastebin.com/9BHRq3Yk

It is something related to morphs.

This is my uc debug: https://gist.github.com/anonymous/7f8d22a1c9aaaa262a02

Thank you. When you can, answer me ;)

**Comment by j0ach1mmall3** [comment]
I see, thanks for opening the report!

**Comment by maxlehot1234** [comment]
No problems. Thanks to you when you can fix it :P

**Comment by j0ach1mmall3** [comment]
Probably fixed in newest JLib builds
