### ISSUE TITLE
Trail particles [Feature]

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#124]
Hi, why the trail particules not follow the player like a real trail !?

Because for the moment, i see 1 particles per 1-2 seconds that follow the player... If you can create something to show a REAL trail, it can be a much better ;)

**Comment by j0ach1mmall3** [comment]
Well the problem is the interval. If you set the interval to 2 seconds, it'll look nicer with the shapes, but for the trail it needs to be like 10 ticks or 5

**Comment by maxlehot1234** [comment]
Ok but is it possible to choose an interval for all shape and anoter interval for trail for example? So with this, this can fix this weird thing ;) Because for the moment, I doesn't use trail cause of this :(

Thanks

**Comment by j0ach1mmall3** [comment]
I don't think it'll be possible
