### ISSUE TITLE
Random particles [FEATURE]

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#125]
Hi, why the random particles are only be near the players feets? They are supposed to be near/around the player, not just feet or I am wrong?

Thanks again if you can add all around the player particles for random ;)

**Comment by j0ach1mmall3** [comment]
Whoops, that's not intended, will fix in a week

**Comment by maxlehot1234** [comment]
Ok nice ;) So no updates this week?

**Comment by j0ach1mmall3** [comment]
Will be fixed in 4.0.3
