### ISSUE TITLE
Join issue 1.8 sometimes (4.0.2)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#126]
Hi, sometimes, when I join my 1.8.8 test server with minecraft 1.8.8, I get this error in the console :
http://pastebin.com/NHNGcwwb

Sometimes, all was great without errors :P

A fix will be nice ;)

**Comment by j0ach1mmall3** [comment]
Weird, can you post /uc debug?

**Comment by maxlehot1234** [comment]
Yes there it is: https://gist.github.com/anonymous/b1ea9d6c908a5c845170
Now I join my test server and doesn't see the error so it is happen sometimes only....
Really weird.

**Comment by j0ach1mmall3** [comment]
I'll fix that in the newest update
