### ISSUE TITLE
Aura rainbow [Feature]

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#127]
Hi, I just want to know if you can add an Aura with rainbow color? So it will use all color instead of just one color.

Thanks

**Comment by j0ach1mmall3** [comment]
Mhmh, probably not

**Comment by maxlehot1234** [comment]
Ok... It is a really good idea, but you are the dev :P

**Comment by j0ach1mmall3** [comment]
Will be added in 4.0.3

**Comment by maxlehot1234** [comment]
It is funny, you say probably not and you add it into the plugin :P :P 
I love them ;)
