### ISSUE TITLE
Some of the cosmetics doesn´t work

### ISSUE THREAD

**Issue by javicalah** [j0ach1mmall3/UltimateCosmetics#130]
Those are the cosmetics that doesn´t work:
- Balloons
- Gadgets
- Block hats (not heads)
- Morphs
- Hearts
- Mounts
- Trails
- Wardrobe
- Particles
- Bowtrails
- Pets

So only 3 or 4 cosmetics work...I´ve paid for it, I need help. And Liv´s disguise doesn´t work on my server so does any other disguising plugin works? Thanks! I love your plugin. My server is running on 1.8.3

**Comment by j0ach1mmall3** [comment]
./uc debug
Console log
Give those
