### ISSUE TITLE
Bows are not working with ultimate cosmetics installed

### ISSUE THREAD

**Issue by hazycraft** [j0ach1mmall3/UltimateCosmetics#131]
There is some bug in ultimate cosmetics rendering all bows on the server entirely useless players are not able to charge bow properly in any server I put ultimate cosmetics on. It does a glitched animation and never fires a arrows.

**Comment by j0ach1mmall3** [comment]
Do you know what cosmetics type is causing it? That'd help out with fixing the bug

**Comment by j0ach1mmall3** [comment]
Can't replicate, can you give me /uc debug?

**Comment by hazycraft** [comment]
I've updated to latest ultimate cosmetics and jlib and the problem released today. Now the problem is fixed
