### ISSUE TITLE
Aura bug 

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#133]
Hi, auras not working on 1.9.x clients now.
I can get the auras, but I see it on me for a maximum of 1 second and it rollback to whitecolor :(
Color disappear directly when I move "the player camera".
Check here: http://imgur.com/pgLYA9S

This is the debug: https://gist.github.com/anonymous/cd4e3225e80851c73bddfcd5387ad082

I really don't where is the problem, because we see them in-game for just 1 second... So it is not a config error... Any fix for this really soon?

Thank you so much.

I use spigot 1.9.x and minecraft 1.9 with latest jlib, ultimatecosmetics version

**Comment by j0ach1mmall3** [comment]
What happens if you remove featherboard?

**Comment by maxlehot1234** [comment]
Nope, same problem... I completely remove featherboard from the plugins folder and still have the issue...

**Comment by j0ach1mmall3** [comment]
And if you try without other plugins?

**Comment by maxlehot1234** [comment]
It works... I will try to put one plugin at a time and check what is the problem... I comment on this if I found the plugin that cause the bug...

**Comment by maxlehot1234** [comment]
I found the problem. It comes from: https://www.spigotmc.org/resources/1-8-pvp-for-1-9.19291/

Are you able to fix this? I will post something on the discussion thread of that plugin, but if you can fix it, it could be nice ;) Because it put oldpvp from 1.8 into 1.9, becaus ethe 1.9 PVP was really bad...
