### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#134]
Hi,

Are you able to add wings builder as another particles types?

Check an example here: https://proxy.spigotmc.org/b5a5f166fa96279a990b07766fabe204bc12828f?url=http%3A%2F%2Fi.imgur.com%2FnifwMTC.gif

Player can choose 1,2 or 3 colors for his wings...

It can be a really cool thing to add ;)

Thanks again

**Comment by j0ach1mmall3** [comment]
I thought about it for a long time, but idk how to do it tbh

**Comment by maxlehot1234** [comment]
I think you can contact kvq on spigot, he developp SuperTrails. Maybe he can help you with this ;)

**Comment by j0ach1mmall3** [comment]
See #137
