### ISSUE TITLE
Proposals for a new gadget

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#14]
It would be better if the gadget "Self Destruct" could throw. By the way, for some reason, nothing is destroyed, and the players did not recoil.

Well, or make other just a new gadget that can do it.

**Comment by j0ach1mmall3** [comment]
Will see about this

**Comment by j0ach1mmall3** [comment]
I will not add new gadgets (because of ammo etc), but I'm open for suggestions to change some gadgets (make them better)
