### ISSUE TITLE
Morph fly problem/bug

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#142]
Hi, when I use morph, the fly was disabled, so I need to do: ./fly to fly again.

If I use GMC, I can't fly after I activate a morph effect... I need to do ./fly :(

Any fix for this?

Thanks

**Comment by j0ach1mmall3** [comment]
IIRC it should only deactivate when using a Morph that has a fly effect, eg. Bat.

**Comment by j0ach1mmall3** [comment]
Best way to prevent this is by not using morphs
