### ISSUE TITLE
Rocket gadget possible glitch...

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#143]
Hi, I fgound a possible usebug/glitch when using the rocket gadgets....

If U se somewhere under the roof and jump, I can pass trough the roof....
Check here: http://i.imgur.com/SmOdTDn.gifv

I think it need to be fix ;)

I use Spigot 1.9.2

**Comment by j0ach1mmall3** [comment]
It's impossible for me to prevent that afaik
