### ISSUE TITLE
Chat spam cooldown

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#144]
Hi, is it possible to reduce the chat spam when someone already use a gadget and wait to use it again.
Check here: http://imgur.com/I1rFAmd

This happens for all things with a cooldown when players spam this cosmetics to use it :P :P
This is bad, maybe reduce 1 message per second instead of multiple 

Thank you so much and sorry for the spam

**Comment by j0ach1mmall3** [comment]
It happens if they click it, they should stop clicking then.
