### ISSUE TITLE
[feature] More permissions ;)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#145]
Hi , I want to know if you can create more permissions into ultimatescosmetics ?

I have a chestcommands menu to allow player to choose, remove and more options for their cosmetics.

So I want to give access to all particles shpaes with 1 permissions like: ultimatecosmetics.particles.*

And I want to know if I can give a player a permission to use all helix particle shap for example:
ultimatecosmetics.particles.shape.helix.*
SAME THING for all comsetics. 

So with this, I can create a really better chestcommands menus and your plugins will become a much better with more permissions I think.

For the moment for chestcommands, I give 1 permission to access all shape for that particle.
In Buycraft, I add all particles permission so players can access all particles too.... This was not the best thing.

Check my setup for the momenthere: http://pastebin.com/79H8GUpf
Like you see in it, all particle shap have the same permission. So if I you can more permission, it would be very nice and I simply need to add them on buycraft ;)

EX: ultimatecosmetics.particles.shape.helix.* -->give access to all particles helix type
EX2: ultimatecosmetics.particles.* -->give access to all particles (all shapes)

In chestcommands, I do the same thing as buycraft or a really similar thing. I simply put the same permission for all particles in all shapes inti these files: http://imgur.com/QN1L4Il

If you have a better idea to how I can produce this ^^^^^^^^^^, it would be nice. If it's not possible, I think a better permissions will be so amazing to have.

Thank you so much and have a nice day/night.

So sorry for this long message and sorry for my bad english :(

**Comment by maxlehot1234** [comment]
EDIT: I change my idea, but more permission will be very nice ;) :P

I use the ./cosmetics menu and multipage setup. 1 page per particles shape ;)
But is it possible to define 1 gui title per page? It could be very nice ;)

**Comment by j0ach1mmall3** [comment]
You can already use the wildcard parameter, depending on your setup.
Say you got 2 particles:
ultimatecosmetics.particles.helix.fire
ultimatecosmetics.particles.dome.voidfog
If a player has ultimatecosmetics.particles.*, it will be able to use all of them.
If a player has ultimatecosmetics.particles.helix.*, it will be able to use the helix one

**Comment by j0ach1mmall3** [comment]
Also, GUI pages might be possible in the feature but then I'll have to redo all the configs

**Comment by maxlehot1234** [comment]
So,
ultimatecosmetics.particles.
was the same aas: ultimatecosmetics.particles.*

Just to be sure ;)


And for GUI pages, it would be very nice if you can, but for the moment, I will add the shape as lore until you redo the config to support per page gui title ;)



Thank you for your fast answer, it is very nice ;)

**Comment by j0ach1mmall3** [comment]
No, you need the asterisk (*) for some reason github removed it
