### ISSUE TITLE
[Feature] Hide something frm GUI's

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#146]
Hi, is it possible to hide these thing from the gui:
http://imgur.com/Ic55TSG

This look bad in gui :P

Thank you so much ;)

**Comment by j0ach1mmall3** [comment]
Use ItemFlags: itemflag:your_item_flag.
More info: https://github.com/j0ach1mmall3/JLib/wiki/The-new-Item-Format

**Comment by maxlehot1234** [comment]
Thank you so much for this ;) I doesn't know that
