### ISSUE TITLE
[Feature] Keep GUI open after remove a cosmetic

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#147]
Hi, I want to know if its possible to add something to keep the gui open when someone remove a particle or any other cosmetic?

With this, he can remove a particle for example and take another cosmetic if he doesn,t to get a particle with a pet for example.

Thank you

**Comment by j0ach1mmall3** [comment]
If I'd add an option for that, I'd have to reset most of the configs so I'll add it in a new update. Also open an issue about the page titles please
