### ISSUE TITLE
Kick from the server directly when I connect (Bungeecoord)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#149]
I each time I try to click on an item in the GUI, I am kick from the server and I am teleported to the lobb server...

I just setup a multi-server setup... So I can't see this problm before

So I decide to remove UltimateCosmetics for the moment...

This is the debug: https://gist.github.com/anonymous/4f3c2e2c98df2e3148c77d5a5545aeef

Thank you so much

PS: I have Spigot 1.9.2 and latest buungeecoord version

**Comment by j0ach1mmall3** [comment]
Any errors?

**Comment by maxlehot1234** [comment]
No no errors, nothing displayed, except that I am kick and tp back to the lobby... I only see that the server (prison server) where I have your plugin installed went down, but this is not true...

**Comment by maxlehot1234** [comment]
I found the problem.

It happen when I doesn't use the UPDATED JLIB version...
This is weird, but I just update jlib and it works fine ;)
