### ISSUE TITLE
Plugin error (doesnt want to work :P )

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#151]
Hi, I update JLIB to latest version and ultimatecosmetics too, but now, cosmetics plugin doesn't work anymore:
When I try to reload the plugin:
http://pastebin.com/jheCkGJv

When the server start:
http://pastebin.com/zPT3iy08

Please fix this problem as soon as possible

**Comment by j0ach1mmall3** [comment]
I am looking into it

**Comment by j0ach1mmall3** [comment]
Duplicate of #150
