### ISSUE TITLE
Aura kick players bungeecoord

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#154]
Hi, when Aura was enabled on 1.9.2 server on my prison server, every players that try to connect are kick and be teleport to the lobby...

I use latest ultimatecosmetics version 4.1.1...

I don't know if its normal or no, but this is very bad...

**Comment by maxlehot1234** [comment]
@j0ach1mmall3 
Directly when I enable aura, I can't reload the plugin (check #153 )
So I think this is anothger problem with your plugin.

**Comment by maxlehot1234** [comment]
@j0ach1mmall3 Any idea why this happen?

**Comment by maxlehot1234** [comment]
@j0ach1mmall3 ?? Please answer me, I really need a fix for this. Thank you

**Comment by j0ach1mmall3** [comment]
It's difficult to fix without an error

**Comment by maxlehot1234** [comment]
I know, but I receive nothing, execept the fact that I am disconnect directly after I login to the server with a message: the server has been down (message from bungeecoord) but the server was never down, I can simply reconnect to it...

This is really bad, because I need auras on my server XD

**Comment by j0ach1mmall3** [comment]
Well, I'll try to look into it

**Comment by maxlehot1234** [comment]
Ok thank you, because it is very bad :(

**Comment by j0ach1mmall3** [comment]
Pretty sure this is a duplicate of #120
