### ISSUE TITLE
Feature trails and random particles

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#155]
Hi, do you know when you can add a real trails particle cosmetics inside your plugin?

Maybe a real random thing too?

Thank you

**Comment by j0ach1mmall3** [comment]
It's already in particles...

**Comment by maxlehot1234** [comment]
I know, but they are so bad... Trails was not a real trails like all other traisl plugin... Becauee particles will be displayed at a really separate interval...

Rnadom are just at feets... Not all around the player

**Comment by j0ach1mmall3** [comment]
Well it's the interval causing issues. I'll fix the random though

**Comment by j0ach1mmall3** [comment]
The random will be fixed in the latest update

**Comment by maxlehot1234** [comment]
Thanks for random one, but PLEASE make them appear all the time, so if the player move, particles follow the players, maybe ONLY for random and trails (when you can make them work...)

It could be really nice, without them, I can't use RANDOM on my server, they are just look really uggly....
Sorry to say this, but this is my opinion...


Thanks again for your plugin and your updates ;)
