### ISSUE TITLE
Reload command error occured...

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#157]
Hi, I just downlaod and installed latest ultimatecosmetics version and I get this message in the console when I try to reload the plugin after enabling auras...
http://pastebin.com/9nMhe78h

Any fix for this when you can?
I need to reload the plugin with Plugman for the moment....

Auras works great, execpt the reload command after enabling them
I try to enable gadgets, auras, morphs, pets and reload the plugin, I get the same error ^^^^^ and this can happen with maybe all other cosmetics things...

If you can fix them, it could be really nice ;)

Thank you so much

**Comment by j0ach1mmall3** [comment]
Please don't use plugman

**Comment by maxlehot1234** [comment]
I AM FORCE to use it because the reload command simply doesn't work...
And NO ISSUE using plugman...

**Comment by j0ach1mmall3** [comment]
The issue is not an issue with my plugin, it's an issue with java. I have no idea to fix it

**Comment by maxlehot1234** [comment]
It is so badd... :( :(

**Comment by j0ach1mmall3** [comment]
Will be fixed in the latest update
