### ISSUE TITLE
List of Bugs in 1.9

### ISSUE THREAD

**Issue by ElPresidentePro** [j0ach1mmall3/UltimateCosmetics#158]
Auras have error and kick tthe player all time.
BannerCape very buged, on movements hide.
Ballons they go away from the position.
Morph need the player see your mob please. similar to Ultracosmetics.

**Comment by j0ach1mmall3** [comment]
All of them are intended, except for the Auras, what's the problem with Auras?

**Comment by ElPresidentePro** [comment]
I select a aura and i have kicked for my server this is a error https://gyazo.com/f34a6bf2669c9b3d61daf51fde2c6142

**Comment by j0ach1mmall3** [comment]
Are you on the latest?

**Comment by ElPresidentePro** [comment]
no sorry i downloaded the laste this problem solved THX

**Comment by ElPresidentePro** [comment]
Error in /uc reload

**Comment by j0ach1mmall3** [comment]
Will be fixed in latest update
