### ISSUE TITLE
Problem inventoryclickevent

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#160]
Hi, I get this problem a lot of times in the console...
http://pastebin.com/CajWKDqW

If you can do something for this, it could be really nice ;)

Thanks again and so sorry for all my reports ;)

**Comment by j0ach1mmall3** [comment]
Weird, my plugin isn't mentioned in the stacktrace...

**Comment by maxlehot1234** [comment]
So what is this:
Could not pass event InventoryClickEvent to UltimateCosmetics v4.1.2
org.bukkit.event.EventException
:P :P

But this spam the console, so I need to uninstall your plugin from my public server... A lot of problem sinc 4.x of ultimatecosmetics :( Too many reports by me...


But thanks for your answer....

**Comment by j0ach1mmall3** [comment]
Yea, but there's none of my classes in the stacktrace, I can't see at all what the issue is. When does it happen?

**Comment by j0ach1mmall3** [comment]
Can you isolate the cause?
