### ISSUE TITLE
Problem with open the GUI

### ISSUE THREAD

**Issue by NickShady** [j0ach1mmall3/UltimateCosmetics#161]
Hey, the first GUI for UC works, Particles works too..., but all other try, i just get a unknow command feedback :/

**Comment by NickShady** [comment]
its something like this... https://gist.github.com/anonymous/47066d150a124527597ffcf5d0ab0e3d

**Comment by j0ach1mmall3** [comment]
There are 2 links, I need them both

**Comment by NickShady** [comment]
if i run the command there are this 3..., 
https://gist.github.com/anonymous/1edd74ba15a14117d87dd64261b8daf0
https://gist.github.com/anonymous/37ebefc3df59815d12815321a6cb375e
https://gist.github.com/anonymous/16de9823010f22c54601b13f63b36a80

but the second from Freeautomessenger..., this plugin is deleted...

**Comment by j0ach1mmall3** [comment]
Show me the startup log

**Comment by NickShady** [comment]
https://gist.github.com/NickShady/965df2988ffef02fdba49115a5ed1a45

**Comment by j0ach1mmall3** [comment]
Doesn't show any issues... Are you sure everything is enabled in the configs?

**Comment by j0ach1mmall3** [comment]
Also that's not the full log

**Comment by NickShady** [comment]
I deleted now all other plugins and try it again, i dont know which plugin cross that, but it works now, so this her can gonna closed

**Comment by NickShady** [comment]
*the problem plugin was "commandoverride"
