### ISSUE TITLE
Issue with the plugin. I don,t know why...

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#162]
Hi, I have this in the console: http://pastebin.com/RrtDkdH4

I don't know why it happens...

Thank you

**Comment by j0ach1mmall3** [comment]
Your data.yml is fucked. Run it through a YAML parser and report back

**Comment by maxlehot1234** [comment]
No error with a yaml parser.... I just test it...

**Comment by j0ach1mmall3** [comment]
can you send the yaml file?

**Comment by maxlehot1234** [comment]
Here it is: http://pastebin.com/Lz94wpi4
It just stock all players UUID, but no one have access right now to cosmetics :P

**Comment by j0ach1mmall3** [comment]
Can't find the issue with the data.yml, but it's a SnakeYAML problem afaik
