### ISSUE TITLE
Error is source code, cannot load com.comphenix.protocol.PacketAdapter

### ISSUE THREAD

**Issue by Joopie123** [j0ach1mmall3/UltimateCosmetics#166]
Hello,

First, thank you for this amazing plugin! I wanted to test it before buying, so i decided to compile the plugin in Eclipse. Eclipse gives the following error:

Description: Resource Path Location	
Type: The project was not built since its build path is incomplete. Cannot find the class file for com.comphenix.protocol.events.PacketAdapter. Fix the build path then try building this project	UltimateCosmetics

Do i need to add extra External Jar Files? Or is it another problem?

**Comment by Joopie123** [comment]
Adding ProtocolLib does nothing...

**Comment by j0ach1mmall3** [comment]
Add protocollib.
Learn to use eclipse.
I won't support building the project by yourself.

**Comment by Joopie123** [comment]
Thank you for your idiot awnser. Dont think that you get any support from me!!
