### ISSUE TITLE
Plugin still using old event system?

### ISSUE THREAD

**Issue by semmeess** [j0ach1mmall3/UltimateCosmetics#168]
Whenever I click through a gui in the plugin, it clicks multiple entries and prompts the unknown command message from spigot.
http://pastebin.com/6jpHPZsx

Causes this error, listed in basically every other plugin running. All on latest 1.8 rev from buildtools.

**Comment by j0ach1mmall3** [comment]
Not really an old event system, but probably a bug on my part. Will try to fix

**Comment by j0ach1mmall3** [comment]
Will be fixed in 4.1.3
