### ISSUE TITLE
Console GUI Open Command 

### ISSUE THREAD

**Issue by MrDip** [j0ach1mmall3/UltimateCosmetics#169]
It'd be very convenient if a small command were programmed into the plugin that could be executed by console that would open the cosmetics menu for a player. Example [/uc open (player)] Thank you :)

**Comment by j0ach1mmall3** [comment]
Pretty sure that's a thing already: /uc open

**Comment by MrDip** [comment]
Command isn't available from in game nor from console.

**Comment by MrDip** [comment]
Correction: the command /uc openmenu is available however when i attempt to open the menu for another player the plugin always responds saying the player is offline.

**Comment by j0ach1mmall3** [comment]
Aha, I'll fix that

**Comment by j0ach1mmall3** [comment]
Fixed in latest update
