### ISSUE TITLE
One small idea for Stackers

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#17]
To enable players stack more than one player. Players who will stacked will emerge at each other above the first player.I think it might be fun.

**Comment by IlPicasso** [comment]
Also the ability to throw the ones you stack 

Like shooting him I dont know how to explain, from a cannon?

**Comment by j0ach1mmall3** [comment]
You can already throw the ones you stack: left click/punch them. As for stacking more than one player, should be possible I think

**Comment by IlPicasso** [comment]
In that case throwing does not seem to be working for me?

**Comment by j0ach1mmall3** [comment]
That's possibly cause you disabled pvp in your server properties
