### ISSUE TITLE
Ultimate Cosmetics Mysql

### ISSUE THREAD

**Issue by MrDip** [j0ach1mmall3/UltimateCosmetics#170]
Have this issue upon startup with Ultimate Cosmetics. 

http://hastebin.com/isefetonuh.avrasm

**Comment by j0ach1mmall3** [comment]
Interesting, will look at that

**Comment by j0ach1mmall3** [comment]
Any other issues?

**Comment by j0ach1mmall3** [comment]
Will be fixed in latest update
