### ISSUE TITLE
Mount Bug/Suggestion

### ISSUE THREAD

**Issue by MinecraftB0ss** [j0ach1mmall3/UltimateCosmetics#172]
Some of the animal mounts have weird ride behavior, almost making them just a statue, not sure if this is a limitation or something that can be refined?

Also, when riding animal mounts over half slabs(and maybe other blocks?) and you arent looking straight, it spams console: http://pastebin.com/sZ0p1HU4

Mob Spawn eggs also go by EntityTag in 1.9, so you cannot specify spawn eggs properly.

**Comment by j0ach1mmall3** [comment]
Mob Spawn eggs are possible, read the documentation at the JLib wiki. Mounts and the like probably can't be fixed unless I use nms.
