### ISSUE TITLE
Data Issue after update

### ISSUE THREAD

**Issue by EthanRPro** [j0ach1mmall3/UltimateCosmetics#174]
Currently getting afew different errors. 

1st - This error randomly occurs during server uptime
http://pastebin.com/LrVeU9JU

2nd - Error occurs when reloading plugin
http://pastebin.com/DxvQvrnX

3rd Errors occur when restarting server
http://pastebin.com/wZTnJJh3

I'm guessing they all stem from the data error when loading the server, the data file claims I should not edit it, which I haven't but I am tempted to delete the data file and have it reload fresh, as I haven't released UC to the public on the server yet. No major data would be lost.

**Comment by j0ach1mmall3** [comment]
can you upload the data.yml?

**Comment by EthanRPro** [comment]
Here is my data file

http://uppit.com/cnyon0ip1euy

**Comment by j0ach1mmall3** [comment]
Error 2 should be fixed
