### ISSUE TITLE
Sure its just a java thing...

### ISSUE THREAD

**Issue by Latamier** [j0ach1mmall3/UltimateCosmetics#181]
Our hosting company - MC Pro Hosting updated Java this morning  and did what ever else they did. 

Since then UC has been screaming in pain on the console. 

Here's the pastebin about it :  [The Red Stuff](http://pastebin.com/Lqv7tX1h)

Thanks, this is really and awesome plugin - worth every penny.

Oh yea - MC 1.10, spigot,

**Comment by j0ach1mmall3** [comment]
Ah this doesn't look like a java thing sadly. The data file is messed up for some reason, and I still don't know how it can happen. Can you upload the file?

**Comment by Latamier** [comment]
Sure thing. I haven't touched that file - as a matter of fact I really haven't altered any of them. 
[datayml](http://pastebin.com/Wv9tFfdm)

**Comment by j0ach1mmall3** [comment]
Yea it's random and automatically, I can't do anything about it because the file is just normal :l

**Comment by Latamier** [comment]
ok I will keep an eye on it. thanks.
