### ISSUE TITLE
new version massive error

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#187]
http://hastebin.com/zukifegeke.avrasm

updated to latest version of Uc and Jlib, rebooted and got spamed to hell with this error

**Comment by j0ach1mmall3** [comment]
Update JLib....

**Comment by zythium** [comment]
i downloaded the latest version from spigot, thats the one that i was linked to,  

https://gyazo.com/7de2607377a52ce41726218ac8e6bd0e

witch takes me to this
https://gyazo.com/a86a3afe12556976503abd0b3193838c

**Comment by zythium** [comment]
im not sure if u realise, but github is out of date for jlib , and says go to spigot, but spigot just sends you back to github! there is no way to actually download a new version of jlib,

**Comment by j0ach1mmall3** [comment]
Ah the jlib build errored, will fix tomorrow
