### ISSUE TITLE
Banner capes Again, (starting to think im gunna be annoying you with all these reports)

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#188]
Banner capes have improved, they actually equip now, but,,,,, although when you first equip them they stay when you dont move and just rotate on the spot, if u walk the cape dissapears, then after a short time it re equips and dissapears again if your'e not stood still.

**Comment by j0ach1mmall3** [comment]
Intended behaviour, it's called the GiveDelay in the config. Afger X seconfs of standing still, they'll re-equip

**Comment by zythium** [comment]
i highly doubt this is intended behavior,   the cape is not equiped,(invisible,gone) whenever u move, it only stays visible if u are not walking, u can rotate on the spot and it will move with u and stay equipped, but if u walk it disappears! then if u stop it will reappear after some time,

**Comment by j0ach1mmall3** [comment]
Yes, this is intended
