### ISSUE TITLE
Failed to load class. 

### ISSUE THREAD

**Issue by Latamier** [j0ach1mmall3/UltimateCosmetics#193]
Just did a reboot and this shown up. Not sure if this is starting the other problem I posted with Jlib or not. 

22.09 20:16:49 [Server] Startup Done! 
22.09 20:16:49 [Server] INFO Switching over to ProtocolLib 
22.09 20:16:49 [Server] INFO Registering Commands... 
22.09 20:16:49 [Server] WARN SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
22.09 20:16:49 [Server] WARN SLF4J: Defaulting to no-operation (NOP) logger implementation 
22.09 20:16:49 [Server] WARN SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
22.09 20:16:49 [Server] INFO Registering Listeners... 
22.09 20:16:49 [Server] INFO Outfits config successfully loaded! 
22.09 20:16:49 [Server] INFO Trails config successfully loaded! 
22.09 20:16:49 [Server] INFO Pets config successfully loaded! 
22.09 20:16:49 [Server] INFO Particles config successfully loaded! 
22.09 20:16:49 [Server] INFO Music config successfully loaded! 
22.09 20:16:49 [Server] INFO Mounts config successfully loaded! 
22.09 20:16:49 [Server] INFO Morphs config successfully loaded! 
22.09 20:16:49 [Server] INFO Hearts config successfully loaded! 
22.09 20:16:49 [Server] INFO Hats config successfully loaded! 
22.09 20:16:49 [Server] INFO Gadgets config successfully loaded! 
22.09 20:16:49 [Server] INFO Fireworks config successfully loaded! 
22.09 20:16:49 [Server] INFO Cloaks config successfully loaded! 
22.09 20:16:49 [Server] INFO BowTrails config successfully loaded! 
22.09 20:16:49 [Server] INFO BlockPets config successfully loaded! 
22.09 20:16:49 [Server] INFO Banners config successfully loaded! 
22.09 20:16:49 [Server] INFO BannerCapes config successfully loaded! 
22.09 20:16:49 [Server] INFO Balloons config successfully loaded! 
22.09 20:16:49 [Server] INFO Auras config successfully loaded! 
22.09 20:16:49 [Server] INFO Loading Modules... 
22.09 20:16:49 [Server] INFO Stacker is enabled in the misc config, but you are running 1.9 or higher. Adjusting that value. 
22.09 20:16:49 [Server] INFO Enabling UltimateCosmetics v4.3.0

**Comment by j0ach1mmall3** [comment]
This is no problem
