### ISSUE TITLE
Snowball effects

### ISSUE THREAD

**Issue by lukeb2014** [j0ach1mmall3/UltimateCosmetics#194]
Is there a way to enable bowtrails for snowballs?

**Comment by lukeb2014** [comment]
I found this code in BowTrailsListener.java:

```@EventHandler
    public void onProjectileLaunch(ProjectileLaunchEvent e) {
        if (e.getEntity() instanceof Arrow) {
            Arrow arrow = (Arrow) e.getEntity();
            if (arrow.getShooter() instanceof Player) {
                Player p = (Player) arrow.getShooter();
                if (this.module.getParent().getApi().hasCosmetics(p, BowTrail.class)) {
                    for(BowTrail cosmetic : this.module.getParent().getApi().getCosmetics(p, BowTrail.class)) {
                        this.module.getArrowsMap().put(arrow, cosmetic);
                    }
                }
            }
        }
    }```

I guess that means that the bowtrails only works for arrows. Could you add the bowtrails to snowballs, or have that as an option in the config?

**Comment by lukeb2014** [comment]
Also I never got the latest version of the plugin working on my sever, I had to use an older version. I tried changing the configs with the latest to the 1.8 configs, but it still didn't work.

**Comment by j0ach1mmall3** [comment]
I could maybe add it, but that kinda doesn't work with the name

**Comment by lukeb2014** [comment]
Yeah true...but for our server we would like to add effects when one shoots a gun, and the projectiles fired by the gun are snowballs.
The plugin we're using for the guns is called Crack Shot.

**Comment by lukeb2014** [comment]
...please? I tried to build the plugin but eclipse keeps blowing up on me.

**Comment by j0ach1mmall3** [comment]
As I said, it doesn't really work with the name so I won't add it
