### ISSUE TITLE
Apears something is missing from data.yml....

### ISSUE THREAD

**Issue by RustyDagger** [j0ach1mmall3/UltimateCosmetics#21]
Ok so this started maybe 2 updates ago when data.yml was changed. and i had to try and move 15,000 lines of user data from one file to another.

Here is the error is now spamming my console with.
http://pastebin.com/b2edrKmW

It apears theres some YML error with data.yml.

What iv done to try and fix it.

I stopped the server and despite my players hating on me I deleted all data.yml And hoped the plugin would make the file again and that would be the end of the issue. But no the files back and I still have the issue. 

The plugin appears to function correctly in game giving and taking ammo as it should.

Im leaving home on a 10 day holiday in a little over 24 hours so if i dont respond that is why.

**Comment by j0ach1mmall3** [comment]
http://wiki.ess3.net/yaml/ try parsing it with this checker. Also, make sure you're on the File storage type

**Comment by RustyDagger** [comment]
I just went to grab the data.yml file to check it and take a look at the files contents....... 

Queue:
  d4158f6b-0164-4ced-ae64-d95cf4539132:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''

YEP thats the whole file, Geee i wonder why the plugins making errors its missing any kind of data...

**Comment by RustyDagger** [comment]
here is a dl link to all my files. I cant for the life of me get it to stop spewing out SnakeYML errors..

https://dl.dropboxusercontent.com/u/15543708/UltimateCosmetics.zip

**Comment by j0ach1mmall3** [comment]
Try setting it to this:
# DO NOT TOUCH THIS FILE!
# EDITING THIS FILE CAN RESULT IN THE PLUGIN BREAKING AND SEVERE DATA LOSS!
# YOU HAVE BEEN WARNED!
Ammo: {}
TreasureChests: {}
Queue: {}
Stacker: {}
DoNotChange: 3.5.1

**Comment by j0ach1mmall3** [comment]
Stupid markdown

**Comment by j0ach1mmall3** [comment]
http://pastebin.com/HJLgZ1xj

**Comment by j0ach1mmall3** [comment]
Is this fixed?

**Comment by RustyDagger** [comment]
yes Your fix seems to of worked.
