### ISSUE TITLE
High Load Plugin

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#22]
http://timings.aikar.co/?url=13518894

Again problem is back must be something related with #16

**Comment by IlPicasso** [comment]
I need help asap

http://imagenes.comugamers.com/i/15-46-09.png

**Comment by IlPicasso** [comment]
Had to remove the plugin because this would freeze my server

**Comment by j0ach1mmall3** [comment]
Well, I can't really make it work async since it doesn't load properly then (see #11 )

**Comment by IlPicasso** [comment]
Which was the build that used async I prefer performance over the sync

**Comment by j0ach1mmall3** [comment]
But then it doesn't load properly...

**Comment by IlPicasso** [comment]
I believe there were only sync problems 

My servers can't simply handle your plugin at the moment they will freeze

**Comment by IlPicasso** [comment]
Is there anyway to disable the on join event

**Comment by j0ach1mmall3** [comment]
No, not really

**Comment by IlPicasso** [comment]
Any solution to this ? 

I am sure I am not the only experiencin this

**Comment by j0ach1mmall3** [comment]
I can, but exams are coming up shortly, so the solution will have to wait a few weeks...

**Comment by j0ach1mmall3** [comment]
This will probably be fixed very soon with the big performance update

**Comment by IlPicasso** [comment]
What is the status of this?

**Comment by j0ach1mmall3** [comment]
I'm almost done with it, just waiting on some final improvements before I release it this friday
