### ISSUE TITLE
Battle Levels implementation for the Hearts

### ISSUE THREAD

**Issue by gunleader** [j0ach1mmall3/UltimateCosmetics#24]
As first asked on the discussion page, I want to give my players the option to color their hearts freely without changing the number of hearts. Because the players get hearts on certain level ups managed by the Battle Levels Plugin.

**Comment by j0ach1mmall3** [comment]
I will look into this

**Comment by j0ach1mmall3** [comment]
So multiple rows won't work on them then?

**Comment by gunleader** [comment]
They work, my problem is only that I need to set a certain amount of hearts in Ultimate Cosmetics, rather than using the current hearts that could change because of lvl ups.

**Comment by gunleader** [comment]
I hope we don't communicate on different things, The players start with 1 Row aka 10 Hearts, after killing things like players or mobs they get a Level Up in Battle Levels, this is completely managed by the plugin.
Now the player has 11 hearts, but I have to give them a certain amount in the cosmetics menu. The hearts have to color minimum 10 up to 20 hearts in a dynamic way.

**Comment by j0ach1mmall3** [comment]
Mhm, I'll see what I can do

**Comment by gunleader** [comment]
Thank you very much

**Comment by j0ach1mmall3** [comment]
Not going to happen, sorry, the situation is too 'niche'
