### ISSUE TITLE
unsupported minor version?

### ISSUE THREAD

**Issue by mmuziek** [j0ach1mmall3/UltimateCosmetics#26]
hi there i get this error :  
... 	6 more
[Java ERROR] 	org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	java.lang.Class.forName(Class.java:264) ~[?:1.7.0]
[Java ERROR] 	java.lang.Class.forName0(Native Method) ~[?:1.7.0]
[Java ERROR] 	java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0]
[Java ERROR] 	java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0]
[Java ERROR] 	org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0]
[Java ERROR] 	java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]
[Java ERROR] 	java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0]
[Java ERROR] 	java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0]
[Java ERROR] 	java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0]
[Java ERROR] 	java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0]
[Java ERROR] 	java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0]
[Java ERROR] 	java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[?:1.7.0]
[Java ERROR] 	java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0]
Caused 	by: java.lang.UnsupportedClassVersionError: com/j0ach1mmall3/ultimatecosmetics/Main : Unsupported major.minor version 52.0
[Java ERROR] 	java.lang.Thread.run(Thread.java:722) [?:1.7.0]
[Java ERROR] 	net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
[Java ERROR] 	org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
org.bukkit.plugin.InvalidPluginException: 	java.lang.UnsupportedClassVersionError: com/j0ach1mmall3/ultimatecosmetics/Main : Unsupported major.minor version 52.0
[11:56:34] 	[Server thread/ERROR] : Could not load 'plugins/UltimateCosmetics.jar' in folder 'plugins'

i use spigot 1.8.8
version 3.5.8 of your plugin
and jlib version 4.1.0

**Comment by j0ach1mmall3** [comment]
You need java 8 for UltimateCosmetics
