### ISSUE TITLE
 Could not pass event PlayerQuitEvent to UltimateCosmetics v3.6.0

### ISSUE THREAD

**Issue by zogoria** [j0ach1mmall3/UltimateCosmetics#27]
Helloe
It happened again, 
I hope you can solve this

http://pastebin.com/wszqdUb5

**Comment by j0ach1mmall3** [comment]
I'll see what I can do about it

**Comment by j0ach1mmall3** [comment]
Does this error occur every time?

**Comment by j0ach1mmall3** [comment]
Try the newest version
