### ISSUE TITLE
Doublr jump issue

### ISSUE THREAD

**Issue by zogoria** [j0ach1mmall3/UltimateCosmetics#28]
Thank you for your great support,
I set permission "ultimatecosmetics.doublejump.true" for the groups that have the double jump access. It works. But now the problem is OPs and owners '*' can not fly because double jump is enables for them,
1- I tried to give them negative permission " -ultimatecosmetics.doublejump.true " but did not solve it,
2- I tried to give them negative permission " -.ultimatecosmetics.doublejump.* "  but did not solve it,
3- I tried to give negative permission " -.ultimatecosmetics.* " It solved the problem and they could fly.
But this means that OPs and Owners Groups, can not use ultimatecosmetics anymore.
Any solution please?

**Comment by j0ach1mmall3** [comment]
Please show your config

**Comment by zogoria** [comment]
http://pastebin.com/PFTbtL46

**Comment by j0ach1mmall3** [comment]
I mean your misc.yml config, sorry for being unclear

**Comment by zogoria** [comment]
Thank you for your awesome support and your immediate response.
http://pastebin.com/W6MSGuV5

**Comment by j0ach1mmall3** [comment]
Try Groups: {}
