### ISSUE TITLE
Ultimate cosmetics error on playerevents

### ISSUE THREAD

**Issue by hazycraft** [j0ach1mmall3/UltimateCosmetics#33]
http://pastebin.com/8PKM5XVL

Ultimate cosmetics throws erros whenever players basically do anything inside the game like using pressure plates, opening doors etc.

I do have stacker, double jump, morphs, mounts ,pets, music and wardrobe disabled in their respected files. I do use libs disguises for morphs, and echo pets for pets/mounts, but do not need the cosmetics menu as I'm creating custom menu with animated menu. Hope this helps thanks. I think that the error may be caused the morph listener still being active even though I have morphs disabled in config.

**Comment by hazycraft** [comment]
I enabled morphs again to see if it would fix the problem and it did.

**Comment by j0ach1mmall3** [comment]
This will be fixed later
