### ISSUE TITLE
The Java file doesn't open???

### ISSUE THREAD

**Issue by Vasterz** [j0ach1mmall3/UltimateCosmetics#34]
I just bought this plugin for I noticed that it had MySQL support, but when I drag the JAVA file to my server plugins section it doesn't open/load. Jlib does load though, but not the UltimateCosmetics JAVA file. Please help as soon as possible! I also tried this on my other mini server to see if the plugin would load but it failed to load even though the only plugins on that mini server which were active at the time was only Jlib and Ultimate Cosmetics... :// Not sure what the problem could be.

*UPDATE:* 
I did some more research on the plugin and it seems that it only runs on Java 8? Is that correct? Thought my hosting company "MCProHosting" was running that, but doesn't seem like it. Contacting them now for an upgrade. So let's see if this will be fixed. Hopefully<3.

Plugin version: Recent one on Spigot.
Server version: 1.8.8
Server type: Spigot
Console log/Crash Report: Console looks fine, just that the file doesn't open/load, etc.

**Comment by j0ach1mmall3** [comment]
Yea, make sure you run java 8. If they don't run it, ask them to update
