### ISSUE TITLE
pets creating "clones" after a player teleports

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#35]
found another bug for you, if a player has a pet spawned and tps far enough away in the same world the old pet turns in to a named normal animal, (this could be an issue with mobs,) thankfully we havent released any pets other than pigs at the moment, so its contained to players plots being full of named pigs, oo and the pet still spawns with the player when they arrive at the other plot far away its like the old on becomes a clone and is left behind

**Comment by j0ach1mmall3** [comment]
Weird, I'll see what I can do about it

**Comment by j0ach1mmall3** [comment]
Fixed in latest update 763ade490ff19bd782c6dceaecef5d38e97fd3f7
