### ISSUE TITLE
colored dust particle, and others,

### ISSUE THREAD

**Issue by zythium** [j0ach1mmall3/UltimateCosmetics#37]
colored dust particle is colored but you cant tell as they are so dark that they all appear various shades of black, recommend adjusting brightness of color, see link: https://gyazo.com/24b5dca6d127f2e47f9ceb7ab92d7a6d

White star particle does nothing,

Hearts particle is blinding due to amount that cover the screen would recommend reducing the spawn rate by 25-50%

potion swirl does not work either,

nor does spell,

thunder cloud is also very overbearing, would recommend reducing amount spawning by 25%-50%

void fog and small smoke are identical,

witch magic does not work.

**Comment by j0ach1mmall3** [comment]
I can't edit the particles. As for the spawn rate, you can modify the interval in the paritcles.yml.
All particles work on my server, are you on 1.7?

**Comment by zythium** [comment]
We are 1.8.   And we have seen and used other particles plugins with the rainbow particles being bright and colourful

**Comment by zythium** [comment]
I would look in to a few other particles plugins and see how they did it. It's definitely possible we actually had one before but it didn't use a gui thus why we switched to urs

**Comment by j0ach1mmall3** [comment]
The particles are pretty bright for me: https://gyazo.com/cb538b0eb637cd309b2ee3aa246bc33c

**Comment by zythium** [comment]
That is very wierd..

**Comment by zythium** [comment]
Would you like to come in my server and see the issues first hand it may help

**Comment by j0ach1mmall3** [comment]
White star, potion swirl, spell and witch magic all work for me.
Make sure you didn't turn down your particle settings in Video Settings

**Comment by j0ach1mmall3** [comment]
What's your server?

**Comment by zythium** [comment]
play.the-ingot.com    pm me in game when your on

**Comment by j0ach1mmall3** [comment]
Try going to Visual Options, and change the particles

**Comment by zythium** [comment]
ok thats that particles sorted then (im dumb) though the colored dust is still a bit dark,
https://gyazo.com/8efef636d91fa5860c7b82dbcec5ad40
https://gyazo.com/af2a02df8f901a8fa0eff345c325146e
ur rainbow dust vs another plugins, the others do work i forgot about my optifine particle settings (had potions effects turned off)
