### ISSUE TITLE
Add Per-Gadget Ammo PlaceHolder in placeholderapi

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#4]
Hello I would like to request placeholders for placeholderapi for example

%ultimatecosmetic_enderbow% and that for each placeholder

**Comment by j0ach1mmall3** [comment]
I will see about that.

**Comment by j0ach1mmall3** [comment]
What will you use it for?

**Comment by IlPicasso** [comment]
Every time a Gadget that uses ammo is shot I want to show how many ammo he/she has left

I also want to put place in my Shop Plugin that uses PlaceHolderApi in the lore of the ammo how many ammo the user has left

**Comment by j0ach1mmall3** [comment]
Well, Clip needs to add it, so it's better you ask him.

**Comment by IlPicasso** [comment]
In that case, you could also add it to your placeholders, so at least in the message when you use your gadget it does not show how many ammo you have

**Comment by j0ach1mmall3** [comment]
I added the %ammoleft% placeholder for that message

**Comment by IlPicasso** [comment]
Awesome thanks!
