### ISSUE TITLE
Problem with UltimateCosmetic

### ISSUE THREAD

**Issue by MangiLP** [j0ach1mmall3/UltimateCosmetics#40]
The System installs correctly, but the commands and menus arent working at all!
Please help me to find a solution, cause i bought much money for your Plugin!

Thanks very much.

**Comment by MangiLP** [comment]
Server Version: 1.8 Spigot
Plugin Version: Newest
Plugin datas: Nothing changed out of the /cosmetics Command to /menu
Error logs: No errors, but dont work at all
Plugin List:
JLIB
ProtocolLib
LibsDisgues
UltimateCosmetic
AnimatedMenu
BlockParticles
BossMessager
CaseOpen
Esentials
Framepicture
Heads+
FurnitureLib
DiceFurniture
Esentials
Essentials GroupManager
Jail
Kitebar
LogBlock
MobRacers
Multiverse-Core
Punish 
RecruitMe
Shop
StaffChat
Staffinventory
SimpleRename
TabOrganaiser
TitleManager
Vault
WorldEdit
WorldGuard

**Comment by j0ach1mmall3** [comment]
What's your java version?

**Comment by IlPicasso** [comment]
Check your log, probably your Plugin is not validating with with the auth server (that always happens to me)

**Comment by j0ach1mmall3** [comment]
So is this fixed?
