### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#41]
In reference with #32 when I place this plugin my lobbies run out of memory at some point, while having them disabled makes them run normally

I tried running timings, but it wont show anything unnusual

**Comment by j0ach1mmall3** [comment]
Well, I improved everything about the plugin I could, I can't really think of anything else

**Comment by IlPicasso** [comment]
The plugin works correctly, awesomely , no TPS issues, but suddenly it ends crashing I will try allocating more memory but still, not sure

I will get the logs too and upload them

**Comment by IlPicasso** [comment]
https://www.dropbox.com/s/5vg5bdrj06dkk98/2015-12-20-7.log?dl=0

**Comment by j0ach1mmall3** [comment]
Whoops, I'll remove that debug message.
Also, I'll look into the memory leak, I think I found the issue, but I'm waiting for confirmation from someone

**Comment by j0ach1mmall3** [comment]
Will be fixed in the next update
