### ISSUE TITLE
Player can't do anything in a certain situation

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#42]
We have 2 players.
Player 1 and Player 2.
Player 2 is on top of Player 1.
Player 2 decides to use the Flying Pig.
Result:
Player 2 will fly on the Pig
Player 1 will be invisible and can't do anything, he is stuck.

**Comment by j0ach1mmall3** [comment]
Weird, I'll investigate that

**Comment by 99IRock** [comment]
If the bug doesn't occurs in your replicate situation then I can always show you on my server.

**Comment by j0ach1mmall3** [comment]
What's your server IP?

**Comment by 99IRock** [comment]
I sent you a private message @Spigot

**Comment by j0ach1mmall3** [comment]
Ok
