### ISSUE TITLE
Hats NPE (Owner Skull)

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#44]
I'm using the pre made Mooshroom Hat and it gives the following NPE. (Every skull with an Owner tag gives a NPE, other materials work fine)

http://pastebin.com/0pCxferH

Version: Spigot 1.8.8 (R0.1)
Plugin version: 3.7.0
Plugins: https://gyazo.com/0da317c845c437b3d3cc28a7259b632e

**Comment by j0ach1mmall3** [comment]
Can you show hats.yml?

**Comment by 99IRock** [comment]
http://pastebin.com/7D98FgEg

There ya go :)

**Comment by j0ach1mmall3** [comment]
It works for me though

**Comment by j0ach1mmall3** [comment]
Aha, it's because the lore is ''
Try setting it to something else, maybe a description of the hat of some sorts
