### ISSUE TITLE
Slime Timer

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#45]
Seems like the Slime Timer is really buggy, I don't have to wait the full 20 seconds. Sometimes I can use it again at 12s, sometimes at 9s, sometimes at 10s. It's really random.

Version: Spigot 1.8.8 (R0.1)
Plugin version: 3.7.0
Plugins: https://gyazo.com/0da317c845c437b3d3cc28a7259b632e

**Comment by j0ach1mmall3** [comment]
All timers on UltimateCosmetics are relative to tps. If your tps is 10, it will takz 2x longer

**Comment by j0ach1mmall3** [comment]
Also, if you use a different gadget while in cooldown, the previous cooldown gets erased

**Comment by 99IRock** [comment]
So then my tps is 40 I guess? Since I can use the slime often 10s before it should be :laughing:

**Comment by j0ach1mmall3** [comment]
Mind my other comment aswell, can you show me your gadgets.yml config?

**Comment by 99IRock** [comment]
http://pastebin.com/FM3cUwS6

There you go :)

**Comment by j0ach1mmall3** [comment]
I'll see what I can do about it
