### ISSUE TITLE
This cosmetic is not enabled Spam On every command.

### ISSUE THREAD

**Issue by RustyDagger** [j0ach1mmall3/UltimateCosmetics#49]
the this cosmetic type is not enabled message is spamming on every command entered in a world where all cosmetics is Denied using the main config file. 

this started after the update with this change log

 Performance fixes

    * Fixes a lot of the performance issues (Huge thanks to @zythium for testing it!)
    * If there are any more issues, please post them on the github 

Again this only happens on the world where all cosmetics are disabled.

here is that part of config.yml
on the kingdom map on any even commands not part of UC it shows the message.

The worlds in which this plugin will not work
 Make sure RemoveCosmeticsOnWorldChange is set to true for this to work correctly
WorldsBlacklist:
- kingdom

**Comment by j0ach1mmall3** [comment]
Leme see about this

**Comment by j0ach1mmall3** [comment]
O I see, whoops, sorry about this error!
