### ISSUE TITLE
Incompatibility with others plugins

### ISSUE THREAD

**Issue by eXtremeCraft** [j0ach1mmall3/UltimateCosmetics#50]
UltimateCosmetics have a problem with Advancedlobby, exactly with the GUI.

The creator have the video, I do not want problems of copies

**Comment by j0ach1mmall3** [comment]
Well, since it's an incompatibility bug with AdvancedLobby, which is a premium plugin, I probably can't reproduce it

**Comment by eXtremeCraft** [comment]
What´s is the problem?

I can speak with the other creator so they can see what happens. (If he wants)

**Comment by j0ach1mmall3** [comment]
Problem is that I won't buy the plugin to reproduce it
