### ISSUE TITLE
RemoveAllCosmetics command

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#54]
You can do so by using the command without [targets] effect is used on a player who uses a command. Or add a variable% player% ? Thanks. I want place this command in menu of cosmetics.

**Comment by j0ach1mmall3** [comment]
I think it's already possible to use %playername% or %player_name%

**Comment by Toshka17** [comment]
Sorry:)

**Comment by Toshka17** [comment]
%playername% and %player_name% 
does not work.
The plugin says "Unknown player"

**Comment by j0ach1mmall3** [comment]
Ah, I'll add it asap then

**Comment by j0ach1mmall3** [comment]
Fixed in 3.8.7
