### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by yetshadow** [j0ach1mmall3/UltimateCosmetics#55]
When I give a group for example; ultimatecosmetics.balloons.whitewool

Players on this group does not have acces to this balloon. 

None permission work for me. 

I can access to cosmetics only if i'm OP

My permissions pluggin is PermissionEx

**Comment by j0ach1mmall3** [comment]
Weird, it works for me when I'm using GroupManager, and I've not gotten any other issues with it from any other users

**Comment by yetshadow** [comment]
I have no error too, so my players can't use it now, they can open the GUI but it say that they do not have the permission to have that kind of cosmetic

**Comment by j0ach1mmall3** [comment]
It also works for me on PEX, what permissions exactly are you giving?

**Comment by yetshadow** [comment]
ultimatecosmetics.balloons.whitewool

uc.give.*

uc.remove.*

uc.* 

ultimatecosmetics.*

I've all tried those and no one work

**Comment by j0ach1mmall3** [comment]
And they can't click on it in the gui? Can you show me your balloons config? (Pastebin)
