### ISSUE TITLE
banners can be removed from the head

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#57]
banners can be removed from the head

**Comment by j0ach1mmall3** [comment]
A bit more context please? Any errors? What did you do?

**Comment by Toshka17** [comment]
https://youtu.be/2YJa524vaMI

**Comment by j0ach1mmall3** [comment]
Maybe because you're in creative

**Comment by Toshka17** [comment]
Yes, it is because of creativity. Then, I think, is not a problem.
