### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by RobinArnhardt** [j0ach1mmall3/UltimateCosmetics#6]
http://hastebin.com/ocubetatup.avrasm

**Comment by IlPicasso** [comment]
While checking logs in the test server I managed to get this
http://pastebin.com/ve7RjhS2

Not sure how to replicate though

**Comment by j0ach1mmall3** [comment]
That's a different bug IlPicasso, please open another issue.

**Comment by j0ach1mmall3** [comment]
Could you try the latest version of JLib?

**Comment by j0ach1mmall3** [comment]
Is this fixed now?
