### ISSUE TITLE
morph nicknames

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#60]
Could you add, please, the ability to morph toggleable to display the nickname.

**Comment by j0ach1mmall3** [comment]
What nickname?

**Comment by Toshka17** [comment]
Add ability to display a players nicknames if that players is used morphs

**Comment by j0ach1mmall3** [comment]
You can probably change that in the libsdisguises config

**Comment by Toshka17** [comment]
Thank you! I have not thought about it

**Comment by Toshka17** [comment]
It did not help. Nicknames is still not visible at
ShowNamesAboveDisguises: true

**Comment by j0ach1mmall3** [comment]
Then it's not possible
