### ISSUE TITLE
For some reason the plug is disconnected from the database

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#63]
http://pastebin.com/rXuGavK8

**Comment by Toshka17** [comment]
I do not know what is it, but ammo not gived

http://pastebin.com/5F1FEaDY

**Comment by j0ach1mmall3** [comment]
I will look into it. Maybe restarting your server would help.

**Comment by Toshka17** [comment]
Yeah, it helps, but it takes a little time and again, there is such a mistake. Nothing is synchronized and is not issued. For my server is critical.

**Comment by Toshka17** [comment]
[12:44:02] [Thread-19/WARN]: Exception in thread "Thread-19" 
[12:44:02] [Thread-19/WARN]: java.lang.NullPointerException
[12:44:02] [Thread-19/WARN]: 	at com.j0ach1mmall3.jlib.storage.database.DatabaseThread.run(DatabaseThread.java:18)

**Comment by Toshka17** [comment]
I understand that after this error, the plugin has stopped working with mysql

**Comment by Toshka17** [comment]
I thought that this is due only to the mysql database and therefore decided to switch to mongodb.

But mongodb going the same mistake!
Maybe the problem jlib?

[02:41:02 WARN]: Exception in thread "Thread-16"
[02:41:02 WARN]: java.lang.NullPointerException
[02:41:02 WARN]:        at com.j0ach1mmall3.ultimatecosmetics.internal.data.MongoDBDataLoader$9.callback(MongoDBDataLoader.java:236)
[02:41:02 WARN]:        at com.j0ach1mmall3.ultimatecosmetics.internal.data.MongoDBDataLoader$9.callback(MongoDBDataLoader.java:233)
[02:41:02 WARN]:        at com.j0ach1mmall3.jlib.storage.database.mongodb.MongoDB$3.run(MongoDB.java:120)
[02:41:02 WARN]:        at com.j0ach1mmall3.jlib.storage.database.DatabaseThread.run(DatabaseThread.java:18)

**Comment by Toshka17** [comment]
http://pastebin.com/3sb0a49X

**Comment by j0ach1mmall3** [comment]
I will see what I can do about it

**Comment by Toshka17** [comment]
It takes only a few minutes after starting server and synchronization stops working.

But this is in my opinion the most beautiful feature in your plugin! This is not nearly anywhere. I very much hope that you solve it.

**Comment by Toshka17** [comment]
With latest UC and Jlib 
Not fixed...
With mongoDB: http://pastebin.com/e5pf8iSw
With Mysql: http://pastebin.com/KcnkMq5h

**Comment by Toshka17** [comment]
Latest jlib and UC: http://pastebin.com/wErFV2Lp

**Comment by j0ach1mmall3** [comment]
Give me the output of /uc debug

**Comment by Toshka17** [comment]
[22:09:01] [Thread-19/WARN]: Exception in thread "Thread-19" 
[22:09:01] [Thread-19/WARN]: java.lang.NullPointerException
[22:09:01] [Thread-19/WARN]: 	at com.j0ach1mmall3.jlib.storage.database.DatabaseThread.run(DatabaseThread.java:18)

https://gist.github.com/anonymous/0c791ecefc36a6cb429d

**Comment by j0ach1mmall3** [comment]
> [22:09:01] [Thread-19/WARN]: Exception in thread "Thread-19" 
> [22:09:01] [Thread-19/WARN]: java.lang.NullPointerException
> [22:09:01] [Thread-19/WARN]: at com.j0ach1mmall3.jlib.storage.database.DatabaseThread.run(DatabaseThread.java:18)
> 
> https://gist.github.com/anonymous/0c791ecefc36a6cb429d

This is fixed in the latest JLib

**Comment by Toshka17** [comment]
Unfortunately, plugin is disconnected from the database so far

After this error (latest update 4.3.0)

http://pastebin.com/mnupGH01

**Comment by j0ach1mmall3** [comment]
Yea, that has nothing to do with JLib, it's MongoDB

**Comment by Toshka17** [comment]
You may suggest something to solve it?
I'll try to use mysql again

**Comment by j0ach1mmall3** [comment]
I will solve it in the newest UC probably

**Comment by Toshka17** [comment]
With mysql is quite not working
http://pastebin.com/Zcuf73f8

**Comment by Toshka17** [comment]
With MySql:
Latest UC, latest Jlib:
Just error: http://pastebin.com/v9JAq4E1

And, connection with base does not work. Because selected cosmetics are not saved when you exit from the server and are not gived when players join to the server. But there are no errors
________________________________________________________
With MongoDB:
Latest UC, latest Jlib:
http://pastebin.com/c6RPXbCn
;'(

**Comment by Toshka17** [comment]
MongoDB: https://gist.github.com/anonymous/b5e42c355c89a9b55a39

**Comment by Toshka17** [comment]
MySql: https://gist.github.com/anonymous/d0197b9a8bbda8ff4c5a

**Comment by j0ach1mmall3** [comment]
Will see what I can do
