### ISSUE TITLE
Only only in x World Option

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#7]
I would like to request a feature to only make Ultimate Cosmetics works on pre defined worlds

**Comment by j0ach1mmall3** [comment]
Permissions?

**Comment by IlPicasso** [comment]
Didn't get , permissions?

**Comment by j0ach1mmall3** [comment]
Yea, just give them permissions per world to use it and remove cosmetics upon world change?

**Comment by IlPicasso** [comment]
Oh my Permissions Manager won't support Per World Permission

**Comment by j0ach1mmall3** [comment]
Well that suck, what do you use?

**Comment by IlPicasso** [comment]
SQLPerms

**Comment by j0ach1mmall3** [comment]
Will be added in the next version
