### ISSUE TITLE
ERROR Spam my Console. Please fix it!

### ISSUE THREAD

**Issue by RobinArnhardt** [j0ach1mmall3/UltimateCosmetics#76]
Hello,

this error: http://prntscr.com/9q9mtm

Spam my console. Please fix it!

Thanks.

**Comment by j0ach1mmall3** [comment]
Duplicate of #70

**Comment by j0ach1mmall3** [comment]
Sorry, my bad, this isn't a duplicate

**Comment by j0ach1mmall3** [comment]
Is this fixed?

**Comment by RobinArnhardt** [comment]
I think, but I'm not sure!
