### ISSUE TITLE
Negative Double Jump permissions

### ISSUE THREAD

**Issue by Toshka17** [j0ach1mmall3/UltimateCosmetics#8]
I added a negative permissions for yourself for double jumps, but I still can use them. How disable doublejump for a player who is '*'

**Comment by j0ach1mmall3** [comment]
I don't think that's possible atm, what permissions plugin do you use?

**Comment by Toshka17** [comment]
Permissionsex

**Comment by j0ach1mmall3** [comment]
Leme see what I can do about it

**Comment by j0ach1mmall3** [comment]
Are you op?

**Comment by Toshka17** [comment]
No, i have permission '*'

**Comment by Toshka17** [comment]
I tried to add all the possible solutions
-ultimatecosmetics.doublejump.*
-ultimatecosmetics.doublejump
-ultimatecosmetics.doublejump.example

**Comment by Toshka17** [comment]
permissions*

**Comment by Toshka17** [comment]
I think it is not critical. Thanks for the support. I can do without it:)
