### ISSUE TITLE
The Connection Error is still standing.

### ISSUE THREAD

**Issue by RobinArnhardt** [j0ach1mmall3/UltimateCosmetics#82]
picture: http://prntscr.com/9tq04w 

What's the mistake?
Are the servers of spigot shut down?

What's happening?
I wish to receive a correct answer ...

**Comment by j0ach1mmall3** [comment]
As mentioned before, it's spigot that's down.
Stop creating issues, it's not a problem with my plugin, sheez

**Comment by RobinArnhardt** [comment]
Spigot is not down! All other Plugin Updater with a function!

And please be a bit more friendly!

**Comment by RobinArnhardt** [comment]
All other Plugins with a Updater Notifications function WORKING!

And please be a bit more friendly!

**Comment by j0ach1mmall3** [comment]
Ok, what other plugin is working then?
