### ISSUE TITLE
MySQL data syncing

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#87]
The MySQL data syncing is not 100%
The pets are not cross server, but the name is.
The selected gadget is not cross server
The selected trail is not cross server
The selected particle is not cross server

**Comment by 99IRock** [comment]
Version: 3.10.3
Bukkit: 1.8.8 R0.1

**Comment by j0ach1mmall3** [comment]
./uc debug
