### ISSUE TITLE
Pet renaming MySQL modus

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#88]
When I rename my pet in MySQL modus my message with the new name input doesn't get blocked as you can see here: https://gyazo.com/c5b8b28f741b82aee2f9510f3e90fada

**Comment by 99IRock** [comment]
Version: 3.10.3
Bukkit: 1.8.8 R0.1

**Comment by j0ach1mmall3** [comment]
./uc debug please

**Comment by j0ach1mmall3** [comment]
It's probably an issue with your Chat plugin
