### ISSUE TITLE
Ultra Intensive OnJoin Issue

### ISSUE THREAD

**Issue by IlPicasso** [j0ach1mmall3/UltimateCosmetics#9]
The plugin UltimateCosmetics is really intensive when OnJoin Event

http://timings.aikar.co/?url=13194291

**Comment by j0ach1mmall3** [comment]
When did this happen? Because it might be very intensive when a player joins and it has to check for updates while Spigot is down.

**Comment by IlPicasso** [comment]
When multiple players joins at the same time for example on a server crash or simply when a minigame server sends the players to the server

"it might be very intensive when a player joins and it has to check for updates while Spigot is down." this too is true

**Comment by j0ach1mmall3** [comment]
I will see what I can do about it

**Comment by IlPicasso** [comment]
New Timings
http://timings.aikar.co/?url=13194742
http://imagenes.comugamers.com/i/10-00-40.png
with 20 players only

**Comment by j0ach1mmall3** [comment]
What about the newest version?

**Comment by IlPicasso** [comment]
not fixed 

http://timings.aikar.co/?url=13210818

**Comment by j0ach1mmall3** [comment]
Oh right, now it's the PlayerKickEvent and the PlayerQuitEvent.
Will be fixed in the next update!

**Comment by IlPicasso** [comment]
seems like it is fixed however I can't say because UC gets disabled most of the times so I never know when it is actually running or not , but so far haven't had any tps issues on my server
