### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by ksiegel22** [j0ach1mmall3/UltimateCosmetics#91]
Not sure what is causing it http://pastebin.com/QaQMU8s3

**Comment by j0ach1mmall3** [comment]
Interesting, never saw that one before. Please /uc debug

**Comment by ksiegel22** [comment]
Here is the debug: https://gist.github.com/anonymous/9baf99a16feb299206ed
Here is a new error: http://pastebin.com/ATGLk7Eq
