### ISSUE TITLE
Paintball Gun Signs

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#94]
Hello, I know this is client side but people can't right mouseclick on the sign because its a block..
This is really annoying :/

**Comment by j0ach1mmall3** [comment]
Tell them to relog

**Comment by j0ach1mmall3** [comment]
It should revert anyway, doesn't it?

**Comment by 99IRock** [comment]
Yes but around +- 50 people need the signs to join the server and they cant if people spam shoot on these signs.

The block does go away it works all fine but I would love it that the signs DONT change in colored blocks

**Comment by j0ach1mmall3** [comment]
Well then I guess I'll "fix" it later
