### ISSUE TITLE
Performance issue (Shape type)

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#96]
Hi, I just try to use shape type with colorfuldust and I get performance issue. TPS drop a little bit and I have this:
http://imgur.com/4GENH72

Is it possible to edit the 3 seconds before get particles for advanced shapes? Like instant particles so particles can ALWAYS follow the players when they move?

Or maybe 1 second not 3 ?

Thank you

**Comment by j0ach1mmall3** [comment]
I need /uc debug
