### ISSUE TITLE
PaintballGun ItemFrame destroyer

### ISSUE THREAD

**Issue by 99IRock** [j0ach1mmall3/UltimateCosmetics#98]
Hey I shot on the ItemFrame and it got destroyed.
Version 3.11.0

**Comment by j0ach1mmall3** [comment]
And it's not back when you relog?

**Comment by 99IRock** [comment]
Nope, just tried that.

**Comment by j0ach1mmall3** [comment]
Debug

**Comment by j0ach1mmall3** [comment]
Will be fixed in a bit
