### ISSUE TITLE
Problem with give command...

### ISSUE THREAD

**Issue by maxlehot1234** [j0ach1mmall3/UltimateCosmetics#99]
Hi, I try to use: ./giveparticles myname particlename 
and I get this error whe using the command on minecraft: http://pastebin.com/2hzFf5mf
and I get this error when execute the command inside the server console: http://pastebin.com/YdKqKpdt

What is the exact command to give a particle and I keep the default particle.yml file os it doesn't come from the config...

I really need to see this work, so I can give particles to my players easily with chestcommands, buycraft, etc

If you need it, this is the debug: https://gist.github.com/anonymous/57b6bae86a3c39117558

Thank you so much

@j0ach1mmall3

**Comment by j0ach1mmall3** [comment]
I'll look into it when I'm back

**Comment by j0ach1mmall3** [comment]
Works for me
